### ISSUE TITLE
Having difficulty replicating tables 5 and 6

### ISSUE THREAD

**Issue by gabbard** [qiangning/TemProb-NAACL18#4]
Running `RunAllThis.sh`, line 1 of table 5 matches the paper and line 2 matches for `dist=1`, but I am not getting a match for `dist=0`.  For `+\eta_b`, `dist=0` the paper has P/R/F `46.2/58.9/51.8` but the file written by `RunAllThis.sh` (`46.3/57.1/51.1`). 

(The production of line 3 is failing altogether; I am looking into this)

I've attached the output:
[Table5_line2.txt](https://github.com/qiangning/TemProb-NAACL18/files/2507375/Table5_line2.txt)

**Comment by gabbard** [comment]
I am having similar problems with table 6, where lines 2 and 3 (both non-baseline lines) do not match (bigger differences this time). I've attached the output files. Any suggestions on where I should look to debug the problem?

[Table6_line3_proposed_noGoldProps.txt](https://github.com/qiangning/TemProb-NAACL18/files/2507400/Table6_line3_proposed_noGoldProps.txt)
[Table6_line2_proposed_noGoldProps.txt](https://github.com/qiangning/TemProb-NAACL18/files/2507401/Table6_line2_proposed_noGoldProps.txt)

**Comment by gabbard** [comment]
Same problem with table 8 - the lines for `proposed` don't match. I suspect this indicates some bug in training?

[Table8_line3_proposed_on_partialTBDense.txt](https://github.com/qiangning/TemProb-NAACL18/files/2507428/Table8_line3_proposed_on_partialTBDense.txt)
[Table8_line6_proposed_on_TBDense.txt](https://github.com/qiangning/TemProb-NAACL18/files/2507429/Table8_line6_proposed_on_TBDense.txt)

**Comment by gabbard** [comment]
It occurs to me that a possible cause of this is that the causality data I found to work around https://github.com/qiangning/TemProb-NAACL18/issues/3 may not be the same as what you ran with for the paper.

**Comment by qiangning** [comment]
Hi Ryan, I tested my code on a different machine and got exactly the same results as I published [here](https://github.com/qiangning/TemProb-NAACL18/tree/master/logs_refs). I also fixed the hard-coded path issue and you can pull it. However, I don't think this file is the reason for the discrepancies here.

For most of the discrepancies you presented here, it's undoubtedly weird, but it's also not critical for drawing the conclusion of that paper, so you can feel free to say `this is what you reproduced via the pkg provided by the authors`. However, I do have a hypothesis that this is due to Gurobi. Which version are you using?

As I said, "for **most** of the discrepancies", which means your results in `Table6_line3_proposed_noGoldProps.txt` and `Table6_line2_proposed_noGoldProps.txt` are indeed problematic: They're exactly the same. I cannot figure out why it's the case, since on my end, what I reproduced is exactly the same as those files I provided [here](https://github.com/qiangning/TemProb-NAACL18/tree/master/logs_refs). Can you double check from your end?

**Comment by gabbard** [comment]
@qiangning : An update - I pulled the updated repo with the causality information and fixed a problem with my Gurobi installation.  The results are now reproducing exactly for Tables 5 and 8.  Table 6 is crashing at the moment due to a Gurobi issue I believe I can fix, so I hope to be able to check those soon.

**Comment by qiangning** [comment]
Thanks @gabbard
